# This manifest file is used to install the required packages for the corresponding notebook.
# The following types of kernels are supported:
# 1. python
# 2. pyodide
# Accordingly, the packages are installed using the kernel type, e.g., packages_pyodide.
# The default packages are installed for all the notebooks.
default:
  packages_common:
    - ase==3.22.1
  packages_python:
    - pymatgen==2023.9.10
  packages_pyodide:
    - lzma
    - sqlite3
    - https://files.mat3ra.com:44318/uploads/pymatgen-2023.9.10-py3-none-any.whl
    - https://files.mat3ra.com:44318/web/pyodide/spglib-2.0.2-py3-none-any.whl
    - https://files.pythonhosted.org/packages/d9/0e/2a05efa11ea33513fbdf4a2e2576fe94fd8fa5ad226dbb9c660886390974/ruamel.yaml-0.17.32-py3-none-any.whl
    - networkx==3.2.1
    - monty==2023.11.3
    - scipy==1.11.2
    - tabulate==0.9.0
    - sympy==1.12
    - uncertainties==3.1.6
notebooks:
  - name: create_interface_with_min_strain_zsl.ipynb
    packages_common:
      - pandas==1.5.3
      - ipywidgets
      - plotly==5.18
      - nbformat>=4.2.0
    packages_python:
    packages_pyodide:
  - name: import_material_from_jarvis_db_entry.ipynb
    packages_common:
      - pandas==1.5.3
      - express-py==2024.2.2.post2
      - mat3ra-esse
      - jarvis-tools
      - munch
      - setuptools
    packages_python:
    packages_pyodide:
      - https://files.mat3ra.com:44318/uploads/paginate-0.5.6-py3-none-any.whl
      - https://files.mat3ra.com:44318/uploads/watchdog-2.3.1-py3-none-any.whl
  - name: import_materials_from_files.ipynb
    packages_common:
      - pandas==1.5.3
      - express-py==2024.2.2.post2
      - mat3ra-esse
      - munch
      - setuptools
    packages_python:
    packages_pyodide:
      - https://files.mat3ra.com:44318/uploads/paginate-0.5.6-py3-none-any.whl
      - https://files.mat3ra.com:44318/uploads/watchdog-2.3.1-py3-none-any.whl
