exclude: ^((examples|other)\/.*\/.*\.(py|poscar|csv))
repos:
  - repo: https://github.com/Exabyte-io/pre-commit-hooks
    rev: 2023.9.13
    hooks:
      - id: ruff
      - id: black
      - id: black-jupyter
        exclude: ^other\/.*\/.*\.ipynb
      - id: isort
      - id: mypy
        exclude: ^examples\/config\.py
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # to strip notebook outputs
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: ^other\/materials_designer\/.*\.ipynb$
