exclude: ^((examples|other)\/.*\/.*\.(py|poscar|csv))
repos:
  - repo: https://github.com/mrakitin/exabyte-io-pre-commit-hooks
    rev: 65b0da1cd8306d3958623bb4a9cadaea32d5f3e9
    hooks:
      - id: ruff
      - id: black
      - id: isort
      - id: mypy
        exclude: ^examples\/config\.py
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
