site_name: Mat3ra API Examples
docs_dir: .
repo_url: https://github.com/Exabyte-io/api-examples

theme:
  name: material
  icon:
    repo: simple/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: "https://docs.mat3ra.com/images/logo/logo-white.png"
  favicon: "https://docs.mat3ra.com/images/logo/favicon.ico"
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: false

copyright: © 2023 <a target="_blank" href="https://mat3ra.com">Exabyte Inc</a>. All rights reserved. | <a target="_blank" href="https://platform.mat3ra.com">Back to platform</a>

extra:
  generator: false

extra_css:
  - extra/css/custom.css

markdown_extensions:
  - codehilite:
      linenums: true
  - footnotes:
      PLACE_MARKER: "///FOOTNOTES GO HERE///"
  - toc:
      permalink: true
  - pymdownx.superfences          # Allow for code blocks "fencing"
  - pymdownx.striphtml            # Strip html comments before processing

nav:
  - Home: README.md
  - Assets:                                                 examples/assets/README.md
  - Get Authentication Params:                              examples/system/get_authentication_params.ipynb
  - Get Workflows:                                          examples/workflow/get_workflows.ipynb
  - Quantum Espresso Workflow and Job:                      examples/workflow/qe_scf_calculation.ipynb
  - Get Materials by Formula:                               examples/material/get_materials_by_formula.ipynb
  - Create Material:                                        examples/material/create_material.ipynb
  - Import Materials from Materials Project:                examples/material/import_materials_from_materialsproject.ipynb
  - Import Materials from Poscar:                           examples/material/import_materials_from_poscar.ipynb
  - Interoperability between Mat3ra and Materials Project:  examples/material/api_interoperability_showcase.ipynb
  - Create and Submit Job:                                  examples/job/create_and_submit_job.ipynb
  - Get File from Job:                                      examples/job/get-file-from-job.ipynb
  - Run Simulations and Extract Properties:                 examples/job/run-simulations-and-extract-properties.ipynb
  - ML - Train Model Predict Properties:                    examples/job/ml-train-model-predict-properties.ipynb

plugins:
  - same-dir

  - search:
      lang: en

  - exclude:
      glob:
        - "other/*"
        - "utils/*.py"
        - "utils/__pycache__/*"
        - "scripts/*"
        - "examples/config.py"
        - "examples/**/*.py"
        - "examples/job/pw_scf.*"
        - "*.egg-info/*"

  - mkdocs-jupyter:
      ignore_h1_titles: true
      include: ["*.ipynb"]  # Default: ["*.py", "*.ipynb"]
      execute: true
      allow_errors: false
      execute_ignore:
        - examples/system/get_authentication_params.ipynb
        - examples/job/run-simulations-and-extract-properties.ipynb
      ignore:
        - "other/**/*.ipynb"
